name: SmartDNS-GFW

on:
  push:
  schedule:
    - cron: '45 19 * * *'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Actions/Checkout
      uses: actions/checkout@main

    - name: Actions/Setup-Python
      uses: actions/setup-python@main
      with:
        python-version: 3.7

    - name: Download Rules
      run: |
        cd smartdns_cn_rules
        wget "https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt" -O gfw.conf
        python rules.py

    - name: Commit
      run: |
        git config --global user.email touma@dymy.org
        git config --global user.name BlackTouma
        git add .
        git commit -m "update" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
